name             'CX-Flask'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures CX-Flask'
long_description 'Installs/Configures CX-Flask'
version          '0.1.0'
